### ISSUE TITLE
Remove requirement for server

### ISSUE THREAD

**Issue by mewejo** [krystal/katapult-whmcs#18]
To use the native WHMCS SSO functionality (to open a console on a VM), it requires a service to be assigned to a server, even with `RequiresServer` marked as `false`, as per https://developers.whmcs.com/provisioning-modules/meta-data-params/

**Expected behaviour**
Allow a user to SSO into a service without a WHMCS server assigned to it.

**Actual behaviour**
WHMCS errors with `Server ID not found.` when trying to SSO into a service without a server assigned to it.

**Workaround**
Setup an empty server for the Katapult module and set it as default, and ensure it is assigned to every Katapult service.

**Comment by MyNamesGeoff** [comment]
Case CORE-16422 now open with WHMCS.
